export const CHARTING_ACTIONS = {
  ENABLE_ANIMATIONS: "ENABLE_ANIMATIONS",
  SET_LINE_TYPE: "SET_LINE_TYPE",
  SET_LEGEND_TYPE: "SET_LEGEND_TYPE",
  SET_ANIMATION_BEGIN: "SET_ANIMATION_BEGIN",
  SET_ANIMATION_DURATION: "SET_ANIMATION_DURATION",
  SET_ANIMATION_EASING: "SET_ANIMATION_EASING"
};
